In [66]:
# Imports
import pandas as pd
from pathlib import Path

In [95]:
salary_df = pd.read_csv(Path("nhl_salary.csv"))

In [96]:
salary_df

                    Player   Tm      Salary     Cap Hit
0           Mikko Rantanen  COL  10,000,000   9,250,000
1              Jack Eichel  VEG  10,000,000  10,000,000
2            Blake Wheeler  WPG  10,000,000   8,250,000
3             Jeff Skinner  BUF  10,000,000   9,000,000
4       Vladimir Tarasenko  STL   9,500,000   7,500,000
..                     ...  ...         ...         ...
727  Jonsson-Fjällby, Axel  WSH     750,000     750,000
728         Attard, Ronnie  PHI     750,000     883,750
729             Foote, Cal  TBL     750,000     850,000
730        Andrew Cogliano  COL     500,000     500,000
731        Derick Brassard  EDM     412,500     412,500

[732 rows x 4 columns]

In [97]:
stats_df = pd.read_csv(Path("NHL_stats.csv"))

In [98]:
stats_df

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,...,SH.1,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%
0,1,Nicholas Abruzzese\abruzni01,22,TOR,C,1,0,0,0,0,...,0,0,NaN,9,9:05,0,0,0,0,NaN
1,2,Noel Acciari\acciano01,30,FLA,C,14,1,4,5,2,...,0,19,5.3,155,11:03,8,35,56,55,50.5
2,3,Calen Addison\addisca01,21,MIN,D,15,2,2,4,-4,...,0,17,11.8,207,13:47,6,12,0,0,NaN
3,4,Andrew Agozzino\agozzan01,31,OTT,LW,1,0,0,0,0,...,0,1,0.0,7,6:52,0,4,1,2,33.3
4,5,Jack Ahcan\ahcanja01,24,BOS,D,5,1,0,1,-2,...,0,4,25.0,74,14:48,3,6,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128,973,Mika Zibanejad\zibanmi01,28,NYR,C,70,27,44,71,26,...,4,192,14.1,1378,19:41,41,55,590,555,51.5
1129,974,Radim Zohorna\zohorra01,25,PIT,F,17,2,4,6,12,...,0,9,22.2,176,10:20,3,23,4,8,33.3
1130,975,Artem Zub\zubar01,26,OTT,D,68,6,15,21,2,...,0,80,7.5,1457,21:26,115,134,0,0,NaN
1131,976,Mats Zuccarello\zuccama01,34,MIN,LW,60,20,49,69,20,...,0,131,15.3,1118,18:38,31,30,19,30,38.8
1132,977,Jason Zucker\zuckeja01,30,PIT,LW,32,6,8,14,3,...,0,89,6.7,488,15:15,15,52,4,10,28.6

In [99]:
stats_df[["Player"]]

                            Player
0     Nicholas Abruzzese\abruzni01
1           Noel Acciari\acciano01
2          Calen Addison\addisca01
3        Andrew Agozzino\agozzan01
4             Jack Ahcan\ahcanja01
...                            ...
1128      Mika Zibanejad\zibanmi01
1129       Radim Zohorna\zohorra01
1130             Artem Zub\zubar01
1131     Mats Zuccarello\zuccama01
1132        Jason Zucker\zuckeja01

[1133 rows x 1 columns]

In [100]:
#string.split(separator, maxsplit)
test_string = "Nicholas Abruzzese\abruzni01"

In [101]:
test_string  = str(test_string )
test_string = test_string.split(os.sep)

In [102]:
test_string[0]

'Nicholas Abruzzese\x07bruzni01'

In [103]:
sep_name= []

for Player in stats_df["Player"]:
    test_string  = str(Player)
    test_string = test_string.split(os.sep)
    sep_name.append(test_string[0])
    print(test_string[0])

Nicholas Abruzzese
Noel Acciari
Calen Addison
Andrew Agozzino
Jack Ahcan
Sebastian Aho
Sebastian Aho
Alexander Alexeyev
Wade Allison
Michael Amadio
Michael Amadio
Michael Amadio
Joey Anderson
Josh Anderson
Michael Anderson
Jaret Anderson-Dolan
Lias Andersson
Rasmus Andersson
Andy Andreoff
Anthony Angello
Mason Appleton
Mason Appleton
Mason Appleton
Josh Archibald
Joel Armia
Viktor Arvidsson
Rasmus Asplund
Zach Aston-Reese
Zach Aston-Reese
Zach Aston-Reese
Andreas Athanasiou
Cam Atkinson
Ronald Attard
Nicolas Aube-Kubel
Nicolas Aube-Kubel
Nicolas Aube-Kubel
Mikael Backlund
Nicklas Backstrom
Brandon Baddock
Sven Baertschi
Kevin Bahl
Josh Bailey
Justin Bailey
Rudolfs Balcers
Alexander Barabanov
Ivan Barbashev
Riley Barber
Aleksander Barkov
Alex Barre-Boulet
Alex Barre-Boulet
Alex Barre-Boulet
Tyson Barrie
Justin Barron
Justin Barron
Justin Barron
Morgan Barron
Morgan Barron
Morgan Barron
Mathew Barzal
Nathan Bastian
Nathan Bastian
Nathan Bastian
Drake Batherson
Gavin Bayreuther
Jay Beagle
Jake Bean
Ethan Bear
Nicolas Beaudin
Nathan Beaulieu
Anthony Beauvillier
Adam Beckman
Pierre-Edouard Bellemare
Kieffer Bellows
Alex Belzile
Emil Bemstrom
Jamie Benn
Jordie Benn
Sam Bennett
Matt Benning
Simon Benoit
Tyler Benson
Patrice Bergeron
Jacob Bernard-Docker
Tyler Bertuzzi
Alex Biega
Brandon Biro
Clark Bishop
Anders Bjork
Kasper Bjorkqvist
Oliver Bjorkstrand
Tobias Bjornfot
Nick Bjugstad
Colin Blackwell
Colin Blackwell
Colin Blackwell
Sammy Blais
Anton Blidh
Teddy Blueger
Brock Boeser
Zach Bogosian
Matt Boldy
Nick Bonino
Adam Boqvist
Jesper Boqvist
William Borgen
Henrik Borgström
Mark Borowiecki
Robert Bortuzzo
Evan Bouchard
Madison Bowey
Travis Boyd
Brian Boyle
Tyler Bozak
Erik Brannstrom
Derick Brassard
Derick Brassard
Derick Brassard
Jesper Bratt
Justin Braun
Justin Braun
Justin Braun
Guillaume Brisebois
Philip Broberg
T.J. Brodie
Jonas Brodin
Jonny Brodzinski
Adam Brooks
Adam Brooks
Adam Brooks
Adam Brooks
Connor Brown
Dustin Brown
Josh Brown
Josh Brown
Josh Brown
Logan Brown
Patrick Brown
Jacob Bryson
Pavel Buchnevich
Connor Bunnaman
Michael Bunting
Andre Burakovsky
Brent Burns
Kyle Burroughs
Will Butcher
Quinton Byfield
Bowen Byram
Paul Byron
Drake Caggiula
Kyle Capobianco
Michael Carcone
Brandon Carlo
John Carlson
Gabriel Carlsson
Lucas Carlsson
Ryan Carpenter
Ryan Carpenter
Ryan Carpenter
Sam Carrick
Alexandre Carrier
William Carrier
Jeff Carter
Jackson Cates
Noah Cates
Cole Caufield
Cody Ceci
Erik Cernak
Thomas Chabot
Zdeno Chara
Jalen Chatfield
Ben Chiarot
Ben Chiarot
Ben Chiarot
Alex Chiasson
Yegor Chinakhov
Declan Chisholm
Sasha Chmelevski
Dennis Cholowski
Jake Christiansen
Jakob Chychrun
Filip Chytil
Anthony Cirelli
Casey Cizikas
Fredrik Claesson
Kale Clague
Kale Clague
Kale Clague
Kyle Clifford
Kyle Clifford
Kyle Clifford
Connor Clifton
Cal Clutterbuck
Dylan Coghlan
Andrew Cogliano
Andrew Cogliano
Andrew Cogliano
Ian Cole
Blake Coleman
Ross Colton
Blake Comeau
J.T. Compher
Max Comtois
Kevin Connauton
Kevin Connauton
Kevin Connauton
Brett Connolly
Kyle Connor
Andrew Copp
Andrew Copp
Andrew Copp
Paul Cotter
Nick Cousins
Logan Couture
Sean Couturier
Charlie Coyle
Dylan Cozens
Kyle Criscuolo
Sidney Crosby
Lawson Crouse
Austin Czarnik
Austin Czarnik
Austin Czarnik
Kirby Dach
Evgenii Dadonov
Jonathan Dahlen
Rasmus Dahlin
Carl Dahlstrom
Michael Dal Colle
Zac Dalpe
Riley Damiani
Phillip Danault
Justin Danforth
Laurent Dauphin
Jeremy Davies
Sean Day
Calvin de Haan
Chase De Leo
Anthony DeAngelo
Alex DeBrincat
Jake DeBrusk
Danny DeKeyser
Michael Del Zotto
Ty Dellandrea
Dylan DeMelo
Grigori Denisenko
Travis Dermott
Travis Dermott
Travis Dermott
Nicolas Deslauriers
Nicolas Deslauriers
Nicolas Deslauriers
Connor Dewar
Jason Dickinson
Brenden Dillon
Cam Dineen
Noah Dobson
Max Domi
Max Domi
Max Domi
Ryan Donato
Joonas Donskoi
Pavel Dorofeyev
Drew Doughty
Nic Dowd
Justin Dowling
Leon Draisaitl
Sheldon Dries
Jonathan Drouin
Jack Drury
Jamie Drysdale
Dillon Dube
Pierre-Luc Dubois
Matt Duchene
Anthony Duclair
Walker Duehr
Brandon Duhaime
Mathew Dumba
Brian Dumoulin
Vince Dunn
Sean Durzi
Christian Dvorak
Ryan Dzingel
Ryan Dzingel
Ryan Dzingel
Cody Eakin
Jordan Eberle
Alexander Edler
Joel Edmundson
Nikolaj Ehlers
Jack Eichel
Aaron Ekblad
Mattias Ekholm
William Eklund
Oliver Ekman-Larsson
Remi Elie
Lars Eller
Ryan Ellis
Pierre Engvall
Tyler Ennis
Mackenzie Entwistle
Loui Eriksson
Joel Eriksson Ek
Adam Erne
Jake Evans
Robby Fabbri
Dante Fabbro
Samuel Fagemo
Radek Faksa
Joel Farabee
Hudson Fasching
Jesper Fast
Justin Faulk
Martin Fehervary
Mario Ferraro
Kevin Fiala
Christian Fischer
Casey Fitzgerald
Trey Fix-Wolansky
Cale Fleury
Haydn Fleury
Warren Foegele
Steven Fogarty
Marcus Foligno
Nick Foligno
Callan Foote
Nolan Foote
Derek Forbort
Alex Formenton
Filip Forsberg
Gustav Forsling
Gabriel Fortier
Liam Foudy
Cam Fowler
Adam Fox
Trent Frederic
Mark Friedman
Martin Frk
Jesper Froden
Morgan Frost
Kurtis Gabriel
Jonah Gadjovich
Sam Gagner
Alex Galchenyuk
Brendan Gallagher
Jakub Galvas
Dylan Gambrell
Rhett Gardner
Conor Garland
Adam Gaudette
Adam Gaudette
Adam Gaudette
Frederick Gaudreau
Johnny Gaudreau
Brendan Gaunce
Frederik Gauthier
Julien Gauthier
Vladislav Gavrikov
Glenn Gawdin
Morgan Geekie
Mason Geertsen
Timothy Gettinger
Ryan Getzlaf
Mark Giordano
Mark Giordano
Mark Giordano
Samuel Girard
Zemgus Girgensons
Claude Giroux
Claude Giroux
Claude Giroux
Cody Glass
Luke Glendening
Alex Goligoski
Barclay Goodrow
Shayne Gostisbehere
Yanni Gourde
Mikael Granlund
Derek Grant
Ryan Graves
Anthony Greco
Andy Greene
Jordan Greenway
A.J. Greer
Noah Gregor
Seth Griffith
Rocco Grimaldi
Jordan Gross
Benoit-Olivier Groulx
Carl Grundstrom
Matt Grzelcyk
Radko Gudas
Erik Gudbranson
Jake Guentzel
Brendan Guhle
Denis Gurianov
David Gustafsson
Erik Gustafsson
Brandon Hagel
Brandon Hagel
Brandon Hagel
Carl Hagelin
Robert Hagg
Robert Hagg
Robert Hagg
Nicolas Hague
Libor Hajek
Jani Hakanpaa
Jayden Halbgewachs
Taylor Hall
Dougie Hamilton
Travis Hamonic
Travis Hamonic
Travis Hamonic
Noah Hanifin
Joel Hanley
Mike Hardman
Jansen Harkins
Thomas Harley
Ben Harpur
Scott Harrington
Jordan Harris
Ryan Hartman
Rafaël Harvey-Pinard
Santeri Hatakka
Garnet Hathaway
Erik Haula
John Hayden
Kevin Hayes
Zack Hayes
Barrett Hayton
Dillon Heatherington
Victor Hedman
Danton Heinen
Ville Heinola
Miro Heiskanen
Darren Helm
Adam Henrique
Aleksi Heponiemi
Tomas Hertl
Thomas Hickey
Matthew Highmore
Cameron Hillis
Vinnie Hinostroza
Roope Hintz
Taro Hirose
Nico Hischier
Hayden Hodgson
Mike Hoffman
Gregory Hofmann
Nils Hoglander
Nick Holden
Justin Holl
Alexander Holtz
Patric Hornqvist
Bo Horvat
Brett Howden
Filip Hronek
Jonathan Huberdeau
Jack Hughes
Quinn Hughes
Brad Hunt
Dryden Hunt
Ben Hutton
Grant Hutton
Zach Hyman
Alex Iafallo
Matt Irwin
Mark Jankowski
Mattias Janmark
Calle Jarnkrok
Calle Jarnkrok
Calle Jarnkrok
Christian Jaros
Seth Jarvis
Dmitrij Jaskin
Tanner Jeannot
Jan Jenik
Boone Jenner
Nick Jensen
Lucas Johansen
Ryan Johansen
Marcus Johansson
Marcus Johansson
Marcus Johansson
Erik Johnson
Jack Johnson
Reese Johnson
Tyler Johnson
Andreas Johnsson
Ross Johnston
Henri Jokiharju
Ben Jones
Caleb Jones
Max Jones
Seth Jones
Zachary Jones
Axel Jonsson Fjällby
Mathieu Joseph
Mathieu Joseph
Mathieu Joseph
Pierre-Olivier Joseph
Dakota Joshua
Roman Josi
Tyson Jost
Tyson Jost
Tyson Jost
Olli Juolevi
Olli Juolevi
Olli Juolevi
Noah Juulsen
Nazem Kadri
Kaapo Kakko
Arthur Kaliyev
Wyatt Kalynuk
David Kampf
Evander Kane
Patrick Kane
Kasperi Kapanen
Kirill Kaprizov
Erik Karlsson
William Karlsson
Ondrej Kase
Zack Kassian
Mark Kastelic
Boris Katchouk
Boris Katchouk
Boris Katchouk
Martin Kaut
Joey Keane
Duncan Keith
Clayton Keller
Parker Kelly
Adrian Kempe
Michal Kempny
Alexander Kerfoot
Tanner Kero
Phil Kessel
Jujhar Khaira
Matt Kiersted
Alex Killorn
Bryce Kindopp
Joel Kiviranta
John Klingberg
Artemi Kniazev
Slater Koekkoek
Otto Koivula
Keegan Kolesar
Vladislav Kolyachonok
Leo Komarov
Travis Konecny
Anze Kopitar
Kaedan Korczak
Klim Kostin
Jesperi Kotkaniemi
Johnathan Kovacevic
Peyton Krebs
Peyton Krebs
Peyton Krebs
Chris Kreider
Torey Krug
Dominik Kubalík
Nikita Kucherov
Karson Kuhlman
Karson Kuhlman
Karson Kuhlman
Dean Kukan
Brett Kulak
Brett Kulak
Brett Kulak
Dmitry Kulikov
Luke Kunin
Janne Kuokkanen
Rasmus Kupari
Sean Kuraly
Philipp Kurashev
Evgeny Kuznetsov
Oliver Kylington
Jordan Kyrou
Kevin Labanc
Andrew Ladd
Paul Ladue
Sam Lafferty
Sam Lafferty
Sam Lafferty
Alexis Lafreniere
William Lagesson
William Lagesson
William Lagesson
Patrik Laine
Maxime Lajoie
Juho Lammikko
Gabriel Landeskog
Hendrix Lapierre
Dylan Larkin
Adam Larsson
Jacob Larsson
Johan Larsson
Johan Larsson
Johan Larsson
Scott Laughton
Jeremy Lauzon
Jeremy Lauzon
Jeremy Lauzon
Curtis Lazar
Brett Leason
Nick Leddy
Nick Leddy
Nick Leddy
Anders Lee
Artturi Lehkonen
Artturi Lehkonen
Artturi Lehkonen
Josh Leivo
Brendan Lemieux
John Leonard
Jake Leschyshyn
Kris Letang
Vinni Lettieri
Tyler Lewington
Trevor Lewis
Timothy Liljegren
Kole Lind
Oskar Lindblom
Petteri Lindbohm
Esa Lindell
Ryan Lindgren
Elias Lindholm
Hampus Lindholm
Hampus Lindholm
Hampus Lindholm
Gustav Lindstrom
Blake Lizotte
Jon Lizotte
William Lockwood
Ryan Lomberg
Steven Lorentz
Adam Lowry
Milan Lucic
Matt Luff
Anton Lundell
Isac Lundestrom
Nils Lundkvist
Eetu Luostarinen
Ilya Lyubushkin
Ilya Lyubushkin
Ilya Lyubushkin
Olli Maatta
Matias Maccelli
Kurtis MacDermid
Jacob MacDonald
Mackenzie MacEachern
Zack MacEwen
Ryan MacInnis
Nathan MacKinnon
Josh Mahura
Cale Makar
Beck Malenstyn
Evgeni Malkin
Brad Malone
Jeff Malott
Mikhail Maltsev
Maxim Mamin
Andrew Mangiapane
Josh Manson
Josh Manson
Josh Manson
Anthony Mantha
Brad Marchand
Jonathan Marchessault
Mason Marchment
John Marino
Mitch Marner
Cooper Marody
Pat Maroon
Matt Martin
Alec Martinez
Jordan Martinook
Mike Matheson
Stefan Matteau
Auston Matthews
Scott Mayfield
Gerald Mayhew
Gerald Mayhew
Gerald Mayhew
Dysin Mayo
Charlie McAvoy
Jake McCabe
Jared McCann
Michael McCarron
Ben McCartney
Max McCormick
Connor McDavid
Ryan McDonagh
Brock McGinn
Greg McKegg
Marc McLaughlin
Michael McLeod
Ryan McLeod
Connor McMichael
Brayden McNabb
Mason Mctavish
Jaycob Megna
Jayson Megna
Timo Meier
Nicolas Meloche
Dawson Mercer
Nicholas Merkley
Ryan Merkley
Dakota Mermis
Jonathon Merrill
Victor Mete
Jacob Middleton
Jacob Middleton
Jacob Middleton
Ilya Mikheyev
Niko Mikkola
Sonny Milano
Colin Miller
J.T. Miller
K'Andre Miller
Daniil Miromanov
Ian Mitchell
Casey Mittelstadt
Sean Monahan
Brandon Montour
John Moore
Trevor Moore
Josh Morrissey
Janis Moser
Tyler Motte
Tyler Motte
Tyler Motte
Jacob Moverare
Connor Murphy
Brett Murray
Ryan Murray
Jake Muzzin
Philippe Myers
Tyler Myers
Vladislav Namestnikov
Vladislav Namestnikov
Vladislav Namestnikov
Riley Nash
Riley Nash
Riley Nash
Riley Nash
James Neal
Martin Necas
Jake Neighbours
Brock Nelson
Patrik Nemeth
Alex Newhook
Valeri Nichushkin
Nino Niederreiter
Markus Niemeläinen
Matthew Nieto
Sami Niku
Stefan Noesen
Mattias Norlinder
Joshua Norris
Tomas Nosek
Thomas Novak
Ryan Nugent-Hopkins
Darnell Nurse
Markus Nutivaara
William Nylander
Gustav Nyquist
Liam O'Brien
Drew O'Connor
Logan O'Connor
Danny O'Regan
Ryan O'Reilly
Jordan Oesterle
Kyle Okposo
Jamie Oleksiak
Mathieu Olivier
Victor Olofsson
Dmitry Orlov
T.J. Oshie
Alex Ovechkin
Brayden Pachal
Max Pacioretty
Jean-Gabriel Pageau
Ondrej Palat
Kyle Palmieri
Artemi Panarin
Richard Panik
Cedric Paquette
Colton Parayko
Zach Parise
David Pastrnak
Greg Pateryn
Nolan Patrick
Nick Paul
Nick Paul
Nick Paul
Joe Pavelski
Chase Pearson
Tanner Pearson
Matthew Peca
Lane Pederson
Andrew Peeke
Adam Pelech
Cole Perfetti
Brendan Perlini
Jacob Perreault
Mathieu Perreault
David Perron
Corey Perry
Scott Perunovich
Brett Pesce
Nic Petan
John-Jason Peterka
Jacob Peterson
Jeff Petry
Elias Pettersson
Marcus Pettersson
Michael Pezzetta
Isaak Phillips
Alex Pietrangelo
Garrett Pilon
Shane Pinto
Neal Pionk
Rem Pitlick
Rem Pitlick
Rem Pitlick
Tyler Pitlick
Tyler Pitlick
Tyler Pitlick
Vasily Podkolzin
Ryan Poehling
Austin Poganski
Brayden Point
Tucker Poolman
Andrew Poturalski
Derrick Pouliot
Derrick Pouliot
Derrick Pouliot
Chase Priskie
Aliaksei Protas
Ivan Provorov
Ethan Prow
Jesse Puljujarvi
Ryan Pulock
Valtteri Puustinen
Mark Pysyk
Jack Quinn
Darren Raddysh
Taylor Raddysh
Taylor Raddysh
Taylor Raddysh
Alexander Radulov
Michael Raffl
Rickard Rakell
Rickard Rakell
Rickard Rakell
Sampo Ranta
Mikko Rantanen
Victor Rask
Victor Rask
Victor Rask
Adam Raska
Michael Rasmussen
Isaac Ratcliffe
Jack Rathbone
Kyle Rau
Lucas Raymond
Ryan Reaves
Scott Reedy
Alec Regula
Kristian Reichel
Lukas Reichel
Mike Reilly
Sam Reinhart
Sheldon Rempal
Dan Renouf
Brad Richardson
Brad Richardson
Brad Richardson
Morgan Rielly
Juuso Riikola
Rasmus Ristolainen
Brett Ritchie
Nick Ritchie
Nick Ritchie
Nick Ritchie
Jason Robertson
Nicholas Robertson
Buddy Robinson
Eric Robinson
Evan Rodrigues
Alexander Romanov
Kevin Rooney
Calle Rosen
Jack Roslovic
Marco Rossi
Antoine Roussel
Carter Rowney
Matt Roy
Nicolas Roy
Kristians Rubins
Chad Ruhwedel
Arttu Ruotsalainen
Kris Russell
Bryan Rust
Jan Rutta
Adam Ruzicka
Derek Ryan
Jonas Røndbjerg
Brandon Saad
Scott Sabourin
Robin Salo
Dylan Samberg
Dmitri Samorukov
Mattias Samuelsson
Linus Sandin
Rasmus Sandin
Zach Sanford
Zach Sanford
Zach Sanford
Travis Sanheim
David Savard
Marco Scandella
Colton Sceviour
Mark Scheifele
Brayden Schenn
Luke Schenn
Nick Schmaltz
Nate Schmidt
Braden Schneider
Corey Schueneman
Justin Schultz
Jaden Schwartz
Cole Schwindt
Nick Seeler
Tyler Seguin
Moritz Seider
Andrej Sekera
Kirill Semyonov
Brett Seney
Mikhail Sergachev
Damon Severson
Michael Sgarbossa
Yegor Sharangovich
Kevin Shattenkirk
Logan Shaw
Mason Shaw
Riley Sheahan
Conor Sheary
Kiefer Sherwood
Kole Sherwood
Devin Shore
Jonas Siegenthaler
Dylan Sikura
Jakob Silfverberg
Cole Sillinger
Radim Simek
Wayne Simmonds
Dominik Simon
Dominik Simon
Dominik Simon
Colton Sissons
Jeff Skinner
Brady Skjei
Jaccob Slavin
Josiah Slavin
Brendan Smith
C.J. Smith
Cole Smith
Craig Smith
Gemel Smith
Givani Smith
Reilly Smith
Ty Smith
Joe Snively
Victor Soderstrom
Egor Sokolov
Carson Soucy
Blake Speers
Jordan Spence
Jason Spezza
Daniel Sprong
Daniel Sprong
Daniel Sprong
Jared Spurgeon
Jordan Staal
Marc Staal
Steven Stamkos
Logan Stanley
Paul Stastny
Troy Stecher
Troy Stecher
Troy Stecher
Sam Steel
Oskar Steen
Alex Steeves
Kevin Stenlund
Derek Stepan
Mitchell Stephens
Chandler Stephenson
Riley Stillman
Mark Stone
Michael Stone
Anton Stralman
Austin Strand
Dylan Strome
Ryan Strome
Marian Studenic
Marian Studenic
Marian Studenic
Jack Studnicka
Nico Sturm
Nico Sturm
Nico Sturm
Tim Stützle
P.K. Subban
C.J. Suess
Oskar Sundqvist
Oskar Sundqvist
Oskar Sundqvist
Andrej Sustr
Andrej Sustr
Andrej Sustr
Pius Suter
Ryan Suter
Nick Suzuki
Andrei Svechnikov
Evgeny Svechnikov
Brandon Tanev
Chris Tanev
Vladimir Tarasenko
Tomas Tatar
John Tavares
Matt Tennyson
Teuvo Teravainen
Troy Terry
Alexandre Texier
Shea Theodore
Robert Thomas
Nate Thompson
Tage Thompson
Tyce Thompson
Lassi Thomson
Joe Thornton
Chris Tierney
Conor Timmins
Jarred Tinordi
Owen Tippett
Owen Tippett
Owen Tippett
Vladimir Tkachev
Brady Tkachuk
Matthew Tkachuk
Devon Toews
Jonathan Toews
Tyler Toffoli
Tyler Toffoli
Tyler Toffoli
Eeli Tolvanen
Philip Tomasino
Dominic Toninato
Alexey Toropchenko
Brayden Tracey
Yakov Trenin
Vincent Trocheck
Jacob Trouba
Alexander True
Alex Tuch
Riley Tufte
Alex Turcotte
Kyle Turris
T.J. Tynan
Urho Vaakanainen
Urho Vaakanainen
Urho Vaakanainen
Juuso Valimaki
James van Riemsdyk
Trevor van Riemsdyk
Frank Vatrano
Frank Vatrano
Frank Vatrano
Mike Vecchione
Lukas Vejdemo
Joe Veleno
Carter Verhaeghe
Kristian Vesalainen
Jimmy Vesey
Jeffrey Viel
Gabriel Vilardi
Alex Vlasic
Marc-Edouard Vlasic
Jakub Voracek
Jakub Vrana
Oliver Wahlstrom
Nathan Walker
Sean Walker
Jake Walman
Jake Walman
Jake Walman
Austin Watson
Jasper Weatherby
MacKenzie Weegar
Alexander Wennberg
Zach Werenski
Blake Wheeler
Colin White
Colton White
Zach Whitecloud
Chris Wideman
Maxwell Willman
Tom Wilson
Luke Witkowski
Christian Wolanin
Christian Wolanin
Christian Wolanin
Miles Wood
Kailer Yamamoto
Keith Yandle
Jesse Ylönen
Cameron York
Pavel Zacha
Filip Zadina
Nikita Zadorov
Nikita Zaitsev
Yegor Zamula
Jakub Zboril
Trevor Zegras
Fabian Zetterlund
Mika Zibanejad
Radim Zohorna
Artem Zub
Mats Zuccarello
Jason Zucker

In [104]:
stats_df["Player"] = pd.DataFrame(sep_name)

In [105]:
print(len(salary_df))
print(len(stats_df))

732
1133

In [106]:
salary_df

                    Player   Tm      Salary     Cap Hit
0           Mikko Rantanen  COL  10,000,000   9,250,000
1              Jack Eichel  VEG  10,000,000  10,000,000
2            Blake Wheeler  WPG  10,000,000   8,250,000
3             Jeff Skinner  BUF  10,000,000   9,000,000
4       Vladimir Tarasenko  STL   9,500,000   7,500,000
..                     ...  ...         ...         ...
727  Jonsson-Fjällby, Axel  WSH     750,000     750,000
728         Attard, Ronnie  PHI     750,000     883,750
729             Foote, Cal  TBL     750,000     850,000
730        Andrew Cogliano  COL     500,000     500,000
731        Derick Brassard  EDM     412,500     412,500

[732 rows x 4 columns]

In [107]:
print(type(salary_df))
print(type(stats_df))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [108]:
stats_df

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,...,SH.1,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%
0,1,Nicholas Abruzzese,22,TOR,C,1,0,0,0,0,...,0,0,NaN,9,9:05,0,0,0,0,NaN
1,2,Noel Acciari,30,FLA,C,14,1,4,5,2,...,0,19,5.3,155,11:03,8,35,56,55,50.5
2,3,Calen Addison,21,MIN,D,15,2,2,4,-4,...,0,17,11.8,207,13:47,6,12,0,0,NaN
3,4,Andrew Agozzino,31,OTT,LW,1,0,0,0,0,...,0,1,0.0,7,6:52,0,4,1,2,33.3
4,5,Jack Ahcan,24,BOS,D,5,1,0,1,-2,...,0,4,25.0,74,14:48,3,6,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128,973,Mika Zibanejad,28,NYR,C,70,27,44,71,26,...,4,192,14.1,1378,19:41,41,55,590,555,51.5
1129,974,Radim Zohorna,25,PIT,F,17,2,4,6,12,...,0,9,22.2,176,10:20,3,23,4,8,33.3
1130,975,Artem Zub,26,OTT,D,68,6,15,21,2,...,0,80,7.5,1457,21:26,115,134,0,0,NaN
1131,976,Mats Zuccarello,34,MIN,LW,60,20,49,69,20,...,0,131,15.3,1118,18:38,31,30,19,30,38.8
1132,977,Jason Zucker,30,PIT,LW,32,6,8,14,3,...,0,89,6.7,488,15:15,15,52,4,10,28.6

In [109]:
stats_df = pd.get_dummies(stats_df,columns=['Tm'])
stats_df

,Rk,Player,Age,Pos,GP,G,A,PTS,+/-,PIM,...,Tm_SEA,Tm_SJS,Tm_STL,Tm_TBL,Tm_TOR,Tm_TOT,Tm_VAN,Tm_VEG,Tm_WPG,Tm_WSH
0,1,Nicholas Abruzzese,22,C,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,2,Noel Acciari,30,C,14,1,4,5,2,4,...,0,0,0,0,0,0,0,0,0,0
2,3,Calen Addison,21,D,15,2,2,4,-4,2,...,0,0,0,0,0,0,0,0,0,0
3,4,Andrew Agozzino,31,LW,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Jack Ahcan,24,D,5,1,0,1,-2,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128,973,Mika Zibanejad,28,C,70,27,44,71,26,12,...,0,0,0,0,0,0,0,0,0,0
1129,974,Radim Zohorna,25,F,17,2,4,6,12,4,...,0,0,0,0,0,0,0,0,0,0
1130,975,Artem Zub,26,D,68,6,15,21,2,46,...,0,0,0,0,0,0,0,0,0,0
1131,976,Mats Zuccarello,34,LW,60,20,49,69,20,20,...,0,0,0,0,0,0,0,0,0,0
1132,977,Jason Zucker,30,LW,32,6,8,14,3,10,...,0,0,0,0,0,0,0,0,0,0

In [110]:
stats_df = pd.get_dummies(stats_df,columns=['Pos'])
stats_df

,Rk,Player,Age,GP,G,A,PTS,+/-,PIM,PS,...,Tm_VAN,Tm_VEG,Tm_WPG,Tm_WSH,Pos_C,Pos_D,Pos_F,Pos_LW,Pos_RW,Pos_W
0,1,Nicholas Abruzzese,22,1,0,0,0,0,0,0.0,...,0,0,0,0,1,0,0,0,0,0
1,2,Noel Acciari,30,14,1,4,5,2,4,0.3,...,0,0,0,0,1,0,0,0,0,0
2,3,Calen Addison,21,15,2,2,4,-4,2,0.3,...,0,0,0,0,0,1,0,0,0,0
3,4,Andrew Agozzino,31,1,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,1,0,0
4,5,Jack Ahcan,24,5,1,0,1,-2,0,0.1,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128,973,Mika Zibanejad,28,70,27,44,71,26,12,8.4,...,0,0,0,0,1,0,0,0,0,0
1129,974,Radim Zohorna,25,17,2,4,6,12,4,0.9,...,0,0,0,0,0,0,1,0,0,0
1130,975,Artem Zub,26,68,6,15,21,2,46,4.8,...,0,0,0,0,0,1,0,0,0,0
1131,976,Mats Zuccarello,34,60,20,49,69,20,20,7.0,...,0,0,0,0,0,0,0,1,0,0
1132,977,Jason Zucker,30,32,6,8,14,3,10,1.2,...,0,0,0,0,0,0,0,1,0,0

In [111]:
stats_df_group_by = stats_df.groupby(by=["Player"]).mean()

In [112]:
stats_df_group_by

,Rk,Age,GP,G,A,PTS,+/-,PIM,PS,EV,...,Tm_VAN,Tm_VEG,Tm_WPG,Tm_WSH,Pos_C,Pos_D,Pos_F,Pos_LW,Pos_RW,Pos_W
Player,,,,,,,,,,,,,,,,,,,,,
A.J. Greer,326.0,25.0,5.0,0.0,0.0,0.0,-1.0,0.0,-0.100,0.0,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Aaron Ekblad,240.0,25.0,61.0,15.0,42.0,57.0,38.0,26.0,9.500,12.0,...,0.0,0.00,0.00,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Adam Beckman,55.0,20.0,3.0,0.0,1.0,1.0,-1.0,2.0,0.000,0.0,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Adam Boqvist,85.0,21.0,44.0,11.0,10.0,21.0,-12.0,10.0,2.600,8.0,...,0.0,0.00,0.00,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Adam Brooks,105.0,25.0,10.5,1.0,0.5,1.5,1.0,1.0,0.125,1.0,...,0.0,0.25,0.25,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zack Hayes,366.0,22.0,3.0,0.0,0.0,0.0,-2.0,0.0,-0.100,0.0,...,0.0,1.00,0.00,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Zack Kassian,450.0,31.0,46.0,5.0,11.0,16.0,-1.0,47.0,1.000,3.0,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Zack MacEwen,555.0,25.0,66.0,2.0,5.0,7.0,-14.0,101.0,-0.600,2.0,...,0.0,0.00,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0
Zdeno Chara,140.0,44.0,59.0,0.0,10.0,10.0,9.0,77.0,3.100,0.0,...,0.0,0.00,0.00,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Zemgus Girgensons,312.0,28.0,44.0,10.0,6.0,16.0,-5.0,25.0,1.400,7.0,...,0.0,0.00,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [113]:
stats_df_group_by.head()
stats_df.head()

,Rk,Player,Age,GP,G,A,PTS,+/-,PIM,PS,...,Tm_VAN,Tm_VEG,Tm_WPG,Tm_WSH,Pos_C,Pos_D,Pos_F,Pos_LW,Pos_RW,Pos_W
0,1,Nicholas Abruzzese,22,1,0,0,0,0,0,0.0,...,0,0,0,0,1,0,0,0,0,0
1,2,Noel Acciari,30,14,1,4,5,2,4,0.3,...,0,0,0,0,1,0,0,0,0,0
2,3,Calen Addison,21,15,2,2,4,-4,2,0.3,...,0,0,0,0,0,1,0,0,0,0
3,4,Andrew Agozzino,31,1,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,1,0,0
4,5,Jack Ahcan,24,5,1,0,1,-2,0,0.1,...,0,0,0,0,0,1,0,0,0,0

In [114]:
df_final = pd.join( stats_df,stats_df_group_by, on='Player',how='outer')

AttributeError: module 'pandas' has no attribute 'join'

In [86]:
df_final.head(20)

,Player,Tm,Salary,Cap Hit,Rk,Age,GP,G,A,PTS,...,HIT,FOW,FOL,FO%,Pos_C,Pos_D,Pos_F,Pos_LW,Pos_RW,Pos_W
0,Mikko Rantanen,COL,"10,000,000","9,250,000",736.0,25.0,66.0,35.0,47.0,82.0,...,50.0,136.0,163.0,45.5,0.0,0.0,0.0,0.0,1.0,0.0
1,Jack Eichel,VEG,"10,000,000","10,000,000",239.0,25.0,23.0,9.0,8.0,17.0,...,28.0,121.0,114.0,51.5,1.0,0.0,0.0,0.0,0.0,0.0
2,Blake Wheeler,WPG,"10,000,000","8,250,000",951.0,35.0,56.0,12.0,42.0,54.0,...,56.0,3.0,13.0,18.8,0.0,0.0,0.0,0.0,1.0,0.0
3,Jeff Skinner,BUF,"10,000,000","9,000,000",831.0,29.0,68.0,28.0,22.0,50.0,...,22.0,74.0,105.0,41.3,0.0,0.0,0.0,1.0,0.0,0.0
4,Vladimir Tarasenko,STL,"9,500,000","7,500,000",887.0,30.0,61.0,23.0,36.0,59.0,...,70.0,4.0,7.0,36.4,0.0,0.0,0.0,0.0,1.0,0.0
5,Oliver Ekman-Larsson,VAN,"9,240,000","7,260,000",243.0,30.0,67.0,4.0,17.0,21.0,...,86.0,0.0,0.0,NaN,0.0,1.0,0.0,0.0,0.0,0.0
6,Justin Faulk,STL,"9,000,000","6,500,000",261.0,29.0,62.0,9.0,25.0,34.0,...,135.0,0.0,0.0,NaN,0.0,1.0,0.0,0.0,0.0,0.0
7,Sidney Crosby,PIT,"9,000,000","8,700,000",177.0,34.0,58.0,26.0,46.0,72.0,...,45.0,614.0,571.0,51.8,1.0,0.0,0.0,0.0,0.0,0.0
8,Anders Lee,NYI,"9,000,000","7,000,000",518.0,31.0,62.0,25.0,16.0,41.0,...,74.0,63.0,66.0,48.8,0.0,0.0,0.0,1.0,0.0,0.0
9,Kevin Hayes,PHI,"9,000,000","7,142,857",365.0,29.0,35.0,8.0,16.0,24.0,...,28.0,188.0,247.0,43.2,0.0,0.0,0.0,0.0,1.0,0.0
10,Brayden Point,TBL,"9,000,000","6,750,000",717.0,25.0,54.0,27.0,27.0,54.0,...,58.0,287.0,281.0,50.5,1.0,0.0,0.0,0.0,0.0,0.0
11,Matthew Tkachuk,CGY,"9,000,000","7,000,000",907.0,24.0,68.0,32.0,52.0,84.0,...,75.0,19.0,19.0,50.0,0.0,0.0,0.0,1.0,0.0,0.0
12,Ryan McDonagh,TBL,"8,400,000","6,750,000",592.0,32.0,60.0,3.0,18.0,21.0,...,82.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
13,Cale Makar,COL,"8,000,000","9,000,000",559.0,23.0,65.0,24.0,51.0,75.0,...,78.0,0.0,0.0,NaN,0.0,1.0,0.0,0.0,0.0,0.0
14,Joe Pavelski,DAL,"8,000,000","7,000,000",685.0,37.0,68.0,25.0,43.0,68.0,...,87.0,325.0,302.0,51.8,1.0,0.0,0.0,0.0,0.0,0.0
15,Brayden Schenn,STL,"8,000,000","6,500,000",796.0,30.0,52.0,19.0,28.0,47.0,...,102.0,223.0,235.0,48.7,1.0,0.0,0.0,0.0,0.0,0.0
16,Ryan Johansen,NSH,"8,000,000","8,000,000",416.0,29.0,65.0,17.0,34.0,51.0,...,56.0,556.0,507.0,52.3,1.0,0.0,0.0,0.0,0.0,0.0
17,Anze Kopitar,LAK,"8,000,000","10,000,000",476.0,34.0,71.0,18.0,41.0,59.0,...,61.0,779.0,577.0,57.4,1.0,0.0,0.0,0.0,0.0,0.0
18,Brock Nelson,NYI,"8,000,000","6,000,000",640.0,30.0,59.0,32.0,17.0,49.0,...,29.0,394.0,399.0,49.7,1.0,0.0,0.0,0.0,0.0,0.0
19,Leon Draisaitl,EDM,"8,000,000","8,500,000",217.0,26.0,70.0,50.0,51.0,101.0,...,43.0,788.0,680.0,53.7,1.0,0.0,0.0,0.0,0.0,0.0

In [26]:
print(df_final.columns.values)

['Rk_x' 'Player' 'Age_x' 'Tm' 'Pos' 'GP_x' 'G_x' 'A_x' 'PTS_x' '+/-_x'
 'PIM_x' 'PS_x' 'EV_x' 'PP_x' 'SH_x' 'GW_x' 'EV.1_x' 'PP.1_x' 'SH.1_x'
 'S_x' 'S%_x' 'TOI_x' 'ATOI' 'BLK_x' 'HIT_x' 'FOW_x' 'FOL_x' 'FO%_x'
 'Rk_y' 'Age_y' 'GP_y' 'G_y' 'A_y' 'PTS_y' '+/-_y' 'PIM_y' 'PS_y' 'EV_y'
 'PP_y' 'SH_y' 'GW_y' 'EV.1_y' 'PP.1_y' 'SH.1_y' 'S_y' 'S%_y' 'TOI_y'
 'BLK_y' 'HIT_y' 'FOW_y' 'FOL_y' 'FO%_y']

In [23]:
df_final.to_csv('df_final.csv')

In [28]:
stats_df.head()
salary_df.head()

               Player   Tm      Salary     Cap Hit
0      Mikko Rantanen  COL  10,000,000   9,250,000
1         Jack Eichel  VEG  10,000,000  10,000,000
2       Blake Wheeler  WPG  10,000,000   8,250,000
3        Jeff Skinner  BUF  10,000,000   9,000,000
4  Vladimir Tarasenko  STL   9,500,000   7,500,000

In [30]:
stats_df.head(20)

,Rk,Player,Age,Tm,Pos,GP,G,A,PTS,+/-,...,SH.1,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%
0,1,Nicholas Abruzzese,22,TOR,C,1,0,0,0,0,...,0,0,NaN,9,9:05,0,0,0,0,NaN
1,2,Noel Acciari,30,FLA,C,14,1,4,5,2,...,0,19,5.3,155,11:03,8,35,56,55,50.5
2,3,Calen Addison,21,MIN,D,15,2,2,4,-4,...,0,17,11.8,207,13:47,6,12,0,0,NaN
3,4,Andrew Agozzino,31,OTT,LW,1,0,0,0,0,...,0,1,0.0,7,6:52,0,4,1,2,33.3
4,5,Jack Ahcan,24,BOS,D,5,1,0,1,-2,...,0,4,25.0,74,14:48,3,6,0,0,NaN
5,6,Sebastian Aho,24,CAR,F,66,31,38,69,16,...,2,189,16.4,1259,19:04,20,68,447,427,51.1
6,7,Sebastian Aho,25,NYI,D,29,1,9,10,-8,...,0,32,3.1,486,16:46,38,23,0,0,NaN
7,8,Alexander Alexeyev,22,WSH,D,1,0,0,0,0,...,0,0,NaN,11,10:35,0,1,0,0,NaN
8,9,Wade Allison,24,PHI,RW,1,0,0,0,-1,...,0,2,0.0,8,8:16,0,1,0,0,NaN
9,10,Michael Amadio,25,TOT,C,45,8,6,14,-2,...,0,49,16.3,534,11:52,13,31,21,34,38.2
10,10,Michael Amadio,25,VEG,C,42,8,6,14,-3,...,0,47,17.0,506,12:04,13,28,21,32,39.6
11,10,Michael Amadio,25,TOR,C,3,0,0,0,1,...,0,2,0.0,27,9:10,0,3,0,2,0.0
12,11,Joey Anderson,23,TOR,RW,4,0,0,0,-1,...,0,8,0.0,31,7:47,0,2,0,0,NaN
13,12,Josh Anderson,27,MTL,RW,56,17,10,27,-22,...,0,122,13.9,968,17:17,28,121,14,17,45.2
14,13,Michael Anderson,22,LAK,D,55,2,5,7,5,...,0,56,3.6,1105,20:05,66,127,0,0,NaN
15,14,Jaret Anderson-Dolan,22,LAK,C,7,0,0,0,-3,...,0,5,0.0,97,13:47,3,12,9,7,56.3
16,15,Lias Andersson,23,LAK,C,18,0,1,1,-6,...,0,23,0.0,196,10:54,2,21,18,22,45.0
17,16,Rasmus Andersson,25,CGY,D,68,4,38,42,21,...,1,124,3.2,1533,22:33,110,45,0,0,NaN
18,17,Andy Andreoff,30,NYI,LW,5,1,0,1,-1,...,0,6,16.7,49,9:52,1,8,6,3,66.7
19,18,Anthony Angello,25,PIT,C,2,0,0,0,0,...,0,2,0.0,12,5:57,0,5,0,1,0.0

In [31]:
stats_df.set_index("Player")

,Rk,Age,Tm,Pos,GP,G,A,PTS,+/-,PIM,...,SH.1,S,S%,TOI,ATOI,BLK,HIT,FOW,FOL,FO%
Player,,,,,,,,,,,,,,,,,,,,,
Nicholas Abruzzese,1,22,TOR,C,1,0,0,0,0,0,...,0,0,NaN,9,9:05,0,0,0,0,NaN
Noel Acciari,2,30,FLA,C,14,1,4,5,2,4,...,0,19,5.3,155,11:03,8,35,56,55,50.5
Calen Addison,3,21,MIN,D,15,2,2,4,-4,2,...,0,17,11.8,207,13:47,6,12,0,0,NaN
Andrew Agozzino,4,31,OTT,LW,1,0,0,0,0,0,...,0,1,0.0,7,6:52,0,4,1,2,33.3
Jack Ahcan,5,24,BOS,D,5,1,0,1,-2,0,...,0,4,25.0,74,14:48,3,6,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Mika Zibanejad,973,28,NYR,C,70,27,44,71,26,12,...,4,192,14.1,1378,19:41,41,55,590,555,51.5
Radim Zohorna,974,25,PIT,F,17,2,4,6,12,4,...,0,9,22.2,176,10:20,3,23,4,8,33.3
Artem Zub,975,26,OTT,D,68,6,15,21,2,46,...,0,80,7.5,1457,21:26,115,134,0,0,NaN
Mats Zuccarello,976,34,MIN,LW,60,20,49,69,20,20,...,0,131,15.3,1118,18:38,31,30,19,30,38.8
Jason Zucker,977,30,PIT,LW,32,6,8,14,3,10,...,0,89,6.7,488,15:15,15,52,4,10,28.6

In [32]:
salary_df.set_index("Player")

                        Tm      Salary     Cap Hit
Player
Mikko Rantanen         COL  10,000,000   9,250,000
Jack Eichel            VEG  10,000,000  10,000,000
Blake Wheeler          WPG  10,000,000   8,250,000
Jeff Skinner           BUF  10,000,000   9,000,000
Vladimir Tarasenko     STL   9,500,000   7,500,000
...                    ...         ...         ...
Jonsson-Fjällby, Axel  WSH     750,000     750,000
Attard, Ronnie         PHI     750,000     883,750
Foote, Cal             TBL     750,000     850,000
Andrew Cogliano        COL     500,000     500,000
Derick Brassard        EDM     412,500     412,500

[732 rows x 3 columns]

In [115]:
df_final = pd.merge( salary_df,stats_df_group_by, on='Player',how='outer')

In [116]:
df_final

,Player,Tm,Salary,Cap Hit,Rk,Age,GP,G,A,PTS,...,Tm_VAN,Tm_VEG,Tm_WPG,Tm_WSH,Pos_C,Pos_D,Pos_F,Pos_LW,Pos_RW,Pos_W
0,Mikko Rantanen,COL,"10,000,000","9,250,000",736.0,25.0,66.0,35.0,47.000000,82.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,Jack Eichel,VEG,"10,000,000","10,000,000",239.0,25.0,23.0,9.0,8.000000,17.000000,...,0.0,1.0,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,Blake Wheeler,WPG,"10,000,000","8,250,000",951.0,35.0,56.0,12.0,42.000000,54.000000,...,0.0,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,Jeff Skinner,BUF,"10,000,000","9,000,000",831.0,29.0,68.0,28.0,22.000000,50.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,Vladimir Tarasenko,STL,"9,500,000","7,500,000",887.0,30.0,61.0,23.0,36.000000,59.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,Zac Dalpe,NaN,NaN,NaN,186.0,32.0,1.0,0.0,0.000000,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1078,Zach Sanford,NaN,NaN,NaN,790.0,27.0,46.0,6.0,6.666667,12.666667,...,0.0,0.0,0.333333,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1079,Zach Werenski,NaN,NaN,NaN,950.0,24.0,60.0,10.0,32.000000,42.000000,...,0.0,0.0,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1080,Zachary Jones,NaN,NaN,NaN,429.0,21.0,11.0,0.0,2.000000,2.000000,...,0.0,0.0,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1081,Zack Hayes,NaN,NaN,NaN,366.0,22.0,3.0,0.0,0.000000,0.000000,...,0.0,1.0,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [117]:
df_final.to_csv('df_final_outer.csv')

In [51]:
df_final.head.describe()

AttributeError: 'function' object has no attribute 'describe'