In [3]:
# Import dependencies
import pandas as pd
import hvplot.pandas
from pathlib import Path

In [4]:
# Read in the CSV file as a Pandas DataFrame
stats_df = pd.read_csv(
    Path("df_final_outer_patrick.csv")
)
stats_df = stats_df.dropna()
stats_df

,Player,Tm,Salary,Cap Hit,Age,GP,G,A,PTS,+/-,...,Tm_TOR,Tm_TOT,Tm_VAN,Tm_VEG,Tm_WPG,Tm_WSH,Pos_C,Pos_D,Pos_LW,Pos_RW
0,Mikko Rantanen,COL,10000000,9250000,25.0,66.000000,35.0,47.0,82.0,32.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Jack Eichel,VEG,10000000,10000000,25.0,23.000000,9.0,8.0,17.0,2.0,...,0.0,0.000000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,Blake Wheeler,WPG,10000000,8250000,35.0,56.000000,12.0,42.0,54.0,-6.0,...,0.0,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,Jeff Skinner,BUF,10000000,9000000,29.0,68.000000,28.0,22.0,50.0,-12.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,Vladimir Tarasenko,STL,9500000,7500000,30.0,61.000000,23.0,36.0,59.0,-3.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,Victor Rask,SEA,4000000,4000000,28.0,22.666667,4.0,6.0,10.0,4.0,...,0.0,0.333333,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
976,Vince Dunn,SEA,4000000,4000000,25.0,64.000000,7.0,22.0,29.0,-18.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
980,William Borgen,SEA,900000,900000,25.0,23.000000,1.0,3.0,4.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
984,Yanni Gourde,SEA,5166666,5166666,30.0,61.000000,17.0,23.0,40.0,-11.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
987,Zachary Jones,NYR,925000,925000,21.0,11.000000,0.0,2.0,2.0,-5.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0